id: P000164
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ᨌ། །བླ་མའི་ཐུགས་སྒྲུབ་རྡོ་རྗེ་དྲག་རྩལ་ལས་ཞལ་གདམས་ལམ་རིམ་ཡེ་ཤེས་སྙིང་པོའི་འགྲེལ་ཡེ་ཤེས་སྣང་བ་རབ་ཏུ་རྒྱས་པ་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་ཡོན་ཏན་རྒྱ་མཚོ།
  layers:
  - book_title
  - author
  - tsawa
  - quotation
  - sabche
  id: KN-LYN-01
web_metadata:
  title:
    en: The Light of Wisdom:A Commentary on Lamrim Yeshe Nyingpo, Gradual Path of
      the Wisdom Essence
    bo: བླ་མའི་ཐུགས་སྒྲུབ་རྡོ་རྗེ་དྲག་རྩལ་ལས་ཞལ་གདམས་ལམ་རིམ་ཡེ་ཤེས་སྙིང་པོའི་འགྲེལ་ཡེ་ཤེས་སྣང་བ་རབ་ཏུ་རྒྱས་པ་ཞེས་བྱ་བ་བཞུགས་སོ།།
  collection:
    en: Lamrim Yeshe Nyingpo–  Book 1
    bo: ''
  author:
    en: Jamgon Kongtrul Lodro Thaye
    bo: ''
  pusblisher:
    en: Ka-Nying Shedrub Publications
    bo: ''
  sku: KN-LYN-01
  category:
    en: Stages of the Path
    bo: ལམ་རིམ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: KN-LYN-01.epub
  description:
    en: ''
    bo: ''
